util::check_argv, util::check_files, util::check_filespec, util::qtd

diff --git a/gim b/gim
--- a/gim
+++ b/gim
@@ -20,6 +20,7 @@ use constant E_ARGUMENTS     =>  6;  # Wrong number of arguments
 use constant E_NOTFILE       =>  7;  # Not a regular file
 use constant E_NOTFILEORDIR  =>  8;  # Not a regular file or directory
 use constant E_NOTTRACKED    =>  9;  # Not a file under version control
+use constant E_INTERNAL      => 10;  # Internal error
 
 ###################################################################
 # Colors
@@ -49,6 +50,7 @@ if ( -t STDOUT )
 }
 
 # Color Scheme
+my $_OK_COL       = $_GREEN;
 my $_ERROR_COL    = $_RED;
 my $_WARN_COL     = $_YELLOW;
 
@@ -158,6 +160,110 @@ package dbg
 # 'util' covers any utility subroutines.
 package util
 {
+    # Check that the number of arguments (remaining @ARGV) is no
+    # less than the first and no more than the second argument.
+    # -1 means 'no check'.
+    sub check_argv( $$ )
+    {
+        dbg::enter();
+
+        if ( @ARGV < $_[0] )
+        {
+            util::throw( ::E_ARGUMENTS, util::text( 'Error: Too few arguments.' ) );
+        }
+
+        if ( ( $_[1] > -1 ) && ( @ARGV > $_[1] ) )
+        {
+            util::throw( ::E_ARGUMENTS, util::text( 'Error: Too many arguments.' ) );
+        }
+
+        dbg::leave();
+    }
+
+    # Throws if one of the arguments does not refer to a file.
+    # Generates warnings for symbolic links, which are not portable
+    # across platforms.
+    sub check_files( @ )
+    {
+        dbg::enter();
+
+        foreach ( @_ )
+        {
+            dbg::msg( "checking ‘$_’" );
+
+            if ( ! -f $_ )
+            {
+                util::throw( ::E_NOTFILE, util::text( 'Error: ‘[_1]’ is not a regular file.', $_ ) );
+            }
+
+            if ( -l $_ )
+            {
+                print( util::text( 'Warning: ‘[_1]’ is a symbolic link, which is not portable.', $_ ) );
+            }
+        }
+
+        dbg::leave();
+    }
+
+    # Check that the list of arguments violates a predicate given
+    # as first parameter. Returns if all arguments check out,
+    # throws otherwise. Generates warnings for symbolic links,
+    # which are not portable across platforms.
+    # Predicates:
+    # ::E_NOTFILE      -- if item is regular file
+    # ::E_NOTFILEORDIR -- if item is regular file or directory
+    # ::E_NOTTRACKED   -- if item is not under version control
+    sub check_filespecs( $@ )
+    {
+        dbg::enter();
+        my $func = shift( @_ );
+
+        foreach ( @_ )
+        {
+            my $filespec = $_;
+            dbg::msg( "checking ‘$filespec’" );
+
+            use feature qw( switch );
+            no warnings qw( experimental::smartmatch );
+
+            given ( $func )
+            {
+                when ( ::E_NOTFILE )
+                {
+                    if ( ! -f $filespec )
+                    {
+                        util::throw( ::E_NOTFILE, util::text( 'Error: ‘[_1]’ is not a regular file.', $filespec ) );
+                    }
+                }
+                when ( ::E_NOTFILEORDIR )
+                {
+                    if ( ! -f $filespec && ! -d $filespec )
+                    {
+                        util::throw( ::E_NOTFILEORDIR, util::text( 'Error: ‘[_1]’ is neither regular file nor directory.', $filespec ) );
+                    }
+                }
+                when ( ::E_NOTTRACKED )
+                {
+                    if ( util::execute( "git ls-files --error-unmatch $filespec" ) )
+                    {
+                        util::throw( ::E_NOTTRACKED, util::text( 'Error: ‘[_1]’ is not under version control.', $filespec ) );
+                    }
+                }
+                default
+                {
+                    util::throw( ::E_INTERNAL, 'Error: Unknown predicate in check_filespecs().' )
+                }
+            }
+
+            if ( -l $filespec )
+            {
+                print( util::text( 'Warning: ‘[_1]’ is a symbolic link, which is not portable.', $_ ) );
+            }
+        }
+
+        dbg::leave();
+    }
+
     # Check return code from external calls
     sub check_rc( $$ )
     {
@@ -254,6 +360,30 @@ package util
         {
             return $rc;
         }
+    }
+
+    # This function quotes its arguments
+    sub qtd( @ )
+    {
+        dbg::enter();
+        my @new;
+
+        foreach ( @_ )
+        {
+            my $need_quotes = m/[ '&\*<>\[\]|\(\);\a\f\n\r\t\v]/;
+
+            s/([\\`"\$])/\\$1/g;
+
+            if ( $need_quotes )
+            {
+                $_ = '"' . $_ . '"';
+            }
+
+            push( @new, $_ );
+        }
+
+        dbg::leave();
+        return @new;
     }
 
     # Pull subcommand from @ARGV.
@@ -471,91 +601,156 @@ package devel
         return ::E_OK;
     }
 
+    # 'devel qtd' runs a couple of tests on util::qtd.
+    package devel::qtd
+    {
+        our @ISA = 'devel';
+
+        sub run()
+        {
+            dbg::enter();
+            my $self = shift( @_ );
+
+            my %tests = ( 'foo bar' => '"foo bar"',
+                          'foo$bar' => "foo\$bar",
+                          'foo&bar' => '"foo&bar"',   # FIXME
+                          'foo*bar' => '"foo*bar"',
+                          'foo<bar' => '"foo<bar"',
+                          'foo`bar' => '"foo\`bar"',  #FIXME
+                          'foo"bar' => '"foo\"bar"',  #FIXME
+                          'foo[bar' => '"foo[bar"',
+                          'foo|bar' => '"foo|bar"',
+                          'foo(bar' => '"foo(bar"',
+                          'foo;bar' => '"foo;bar"',
+                          'foo\bar' => '"foo\\bar"',  # FIXME
+                          'foo	bar' => '"foo	bar"',
+                        );
+
+            my @quoted = util::qtd( keys %tests );
+
+            while ( my ( $expected, $input ) = sort each %tests )
+            {
+                my $observed = shift( @quoted );
+
+                printf( "%10s -> %10s ... ", $input, $expected );
+
+                if ( $observed eq $expected )
+                {
+                    printf( "%s%s%s\n", $_OK_COL, "OK", $_RESET );
+                }
+                else
+                {
+                    printf( "%s%s%s (got: %s)\n", $_ERROR_COL, "ERR", $_RESET, $observed );
+                }
+            }
+
+            dbg::leave();
+        }
+    }
+
     # 'devel test' runs a list of regression tests.
     package devel::test
     {
-        dbg::enter();
-        my $self = shift( @_ );
-        my ( $rc, $output );
+        our @ISA = 'devel';
 
-        # preparing test executable
-        ( my $testexe = q{#!/usr/bin/env bash
-
-        o=1
-        e=1
-
-        for arg in "$@"
-        do
-            case $arg in
-                o)
-                    echo "stdout$o"
-                    o=$(($o + 1))
-                    ;;
-                e)
-                    echo "stderr$e" >&2
-                    e=$(($e + 1))
-                    ;;
-                [0-9])
-                    exit $arg
-                    ;;
-                s)
-                    kill -s SIGINT $$
-                    ;;
-            esac
-        done
-        }) =~ s/^ {8}//mg;
-        open( my $fh, '>', 'testexe' ) || die( "Error: Could not open 'testexe' for writing.\n" . $! );
-        print( $fh $testexe );
-        close( $fh );
-        chmod( 0755, 'testexe' );
-        print( "Running self-tests:\n" );
-
-        # util::execute()
-        my $expected = "stdout1\nstdout2\nstdout3\nstderr1\nstdout4\nstdout5\nstdout6";
-        eval { util::execute( 'nosuchcommand' ); }; die unless ( $@ =~ /.*Error:.* Failed to execute ‘nosuchcommand’\.\nCommand not found\./ );
-        $rc = util::execute( './testexe o o o e o o o 0' ); die unless ( $rc == 0 );
-        $rc = util::execute( './testexe o o o e o o o 1' ); die unless ( $rc == 1 );
-        eval { util::execute( './testexe o o o e o o o s' ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
-        $rc = util::execute( './testexe o o o e o o o 0', rc => 0 ); die unless ( $rc == 0 );
-        $rc = util::execute( './testexe o o o e o o o 1', rc => 0 ); die unless ( $rc == 1 );
-        eval { util::execute( './testexe o o o e o o o s', rc => 0 ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
-        $rc = util::execute( './testexe o o o e o o o 0', rc => -1 ); die unless ( $rc == 0 );
-        eval { util::execute( './testexe o o o e o o o 1', rc => -1 ); }; die unless ( $@ =~ /.*Error:.* Failed to execute ‘devel’\.\n.*‘\.\/testexe o o o e o o o 1’ returned ‘1’:\n$expected/ );
-        eval { util::execute( './testexe o o o e o o o s', rc => -1 ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
-        ( $rc, $output ) = util::execute( './testexe 0', out => 1 ); die unless ( ( $rc == 0 ) && ( $output eq '' ) );
-        ( $rc, $output ) = util::execute( './testexe 1', out => 1 ); die unless ( ( $rc == 1 ) && ( $output eq '' ) );
-        ( $rc, $output ) = util::execute( './testexe o o o e o o o 0', out => 1 ); die unless ( $rc == 0 && $output eq $expected );
-        ( $rc, $output ) = util::execute( './testexe o o o e o o o 1', out => 1 ); die unless ( $rc == 1 && $output eq $expected );
-        eval { util::execute( './testexe o o o e o o o s', out => 1 ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
-
-        # executor
-        my $exe;
-        eval { $exe = new executor( 'nosuchcommand' ); }; die unless ( $@ =~ /.*Error:.* Failed to execute ‘nosuchcommand’\./ );
-        $exe = new executor( './testexe o o o e o o o 0' );
-        $rc = 1;
-        while ( $exe->readline() )
+        sub run()
         {
-            chomp;
-            die unless ( $_ eq "stdout$rc" );
-            ++$rc;
+            dbg::enter();
+            my $self = shift( @_ );
+            util::check_argv( -1, 0 );
+            my ( $rc, $output );
+
+            # preparing test executable
+            ( my $testexe = q{#!/usr/bin/env bash
+
+            o=1
+            e=1
+
+            for arg in "$@"
+            do
+                case $arg in
+                    o)
+                        echo "stdout$o"
+                        o=$(($o + 1))
+                        ;;
+                    e)
+                        echo "stderr$e" >&2
+                        e=$(($e + 1))
+                        ;;
+                    [0-9])
+                        exit $arg
+                        ;;
+                    s)
+                        kill -s SIGINT $$
+                        ;;
+                esac
+            done
+            }) =~ s/^ {8}//mg;
+            open( my $fh, '>', 'testexe' ) || die( "Error: Could not open 'testexe' for writing.\n" . $! );
+            print( $fh $testexe );
+            close( $fh );
+            chmod( 0755, 'testexe' );
+            print( "Running self-tests:\n" );
+
+            # util::execute()
+            my $expected = "stdout1\nstdout2\nstdout3\nstderr1\nstdout4\nstdout5\nstdout6";
+            eval { util::execute( 'nosuchcommand' ); }; die unless ( $@ =~ /.*Error:.* Failed to execute ‘nosuchcommand’\.\nCommand not found\./ );
+            $rc = util::execute( './testexe o o o e o o o 0' ); die unless ( $rc == 0 );
+            $rc = util::execute( './testexe o o o e o o o 1' ); die unless ( $rc == 1 );
+            eval { util::execute( './testexe o o o e o o o s' ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
+            $rc = util::execute( './testexe o o o e o o o 0', rc => 0 ); die unless ( $rc == 0 );
+            $rc = util::execute( './testexe o o o e o o o 1', rc => 0 ); die unless ( $rc == 1 );
+            eval { util::execute( './testexe o o o e o o o s', rc => 0 ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
+            $rc = util::execute( './testexe o o o e o o o 0', rc => -1 ); die unless ( $rc == 0 );
+            eval { util::execute( './testexe o o o e o o o 1', rc => -1 ); }; die unless ( $@ =~ /.*Error:.* Failed to execute ‘devel’\.\n.*‘\.\/testexe o o o e o o o 1’ returned ‘1’:\n$expected/ );
+            eval { util::execute( './testexe o o o e o o o s', rc => -1 ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
+            ( $rc, $output ) = util::execute( './testexe 0', out => 1 ); die unless ( ( $rc == 0 ) && ( $output eq '' ) );
+            ( $rc, $output ) = util::execute( './testexe 1', out => 1 ); die unless ( ( $rc == 1 ) && ( $output eq '' ) );
+            ( $rc, $output ) = util::execute( './testexe o o o e o o o 0', out => 1 ); die unless ( $rc == 0 && $output eq $expected );
+            ( $rc, $output ) = util::execute( './testexe o o o e o o o 1', out => 1 ); die unless ( $rc == 1 && $output eq $expected );
+            eval { util::execute( './testexe o o o e o o o s', out => 1 ); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
+
+            # executor
+            my $exe;
+            eval { $exe = new executor( 'nosuchcommand' ); }; die unless ( $@ =~ /.*Error:.* Failed to execute ‘nosuchcommand’\./ );
+            $exe = new executor( './testexe o o o e o o o 0' );
+            $rc = 1;
+            while ( $exe->readline() )
+            {
+                chomp;
+                die unless ( $_ eq "stdout$rc" );
+                ++$rc;
+            }
+            $exe->close();
+            die unless ( $exe->{ linecount } == 6 );
+            die unless ( $exe->{ errors } eq "stderr1\n" );
+            die unless ( $exe->{ rc } == 0 );
+            $exe = new executor( './testexe o o o e o o o 1' ); $exe->close(); die unless ( $exe->{ rc } == 1 );
+            $exe = new executor( './testexe o o o e o o o s' ); eval { $exe->close(); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
+
+            # util::subcommand()
+            ( util::execute( "$0" ) == ::E_SUB_MISSING ) || die;
+            ( util::execute( "$0 foo" ) == ::E_SUB_UNKNOWN ) || die;
+            ( util::execute( "$0 worker" ) == ::E_SUB_UNKNOWN ) || die;
+            ( util::execute( "$0 devel" ) == ::E_SUB_MISSING ) || die;
+
+            # check_argv()
+            @ARGV = (); util::check_argv( -1, -1 );
+            @ARGV = (); util::check_argv( 0, 0 );
+            @ARGV = ( 1 ); util::check_argv( -1, 1 );
+            @ARGV = ( 1 ); util::check_argv( 0, 1 );
+            @ARGV = ( 1 ); util::check_argv( 1, 1 );
+            @ARGV = ( 1 ); util::check_argv( 1, 2 );
+            @ARGV = ( 1 ); eval { util::check_argv( 0, 0 ); }; if ( $@ ) { die unless $@ =~ /.*Error:.* Too many arguments./; }
+            @ARGV = ( ); eval { util::check_argv( 1, 1 ); }; if ( $@ ) { die unless $@ =~ /.*Error:.* Too few arguments./; }
+            @ARGV = ( 1, 2 ); eval { util::check_argv( 1, 1 ); }; if ( $@ ) { die unless $@ =~ /.*Error:.* Too many arguments./; }
+            @ARGV = ( 1, 2 ); eval { util::check_argv( 2, 2 ); }; if ( $@ ) { die unless $@ =~ /.*Error:.* Too few arguments./; }
+
+            # Clean up
+            unlink( 'testexe' );
+            print( "Done.\n" );
+            dbg::leave();
         }
-        $exe->close();
-        die unless ( $exe->{ linecount } == 6 );
-        die unless ( $exe->{ errors } eq "stderr1\n" );
-        die unless ( $exe->{ rc } == 0 );
-        $exe = new executor( './testexe o o o e o o o 1' ); $exe->close(); die unless ( $exe->{ rc } == 1 );
-        $exe = new executor( './testexe o o o e o o o s' ); eval { $exe->close(); }; die unless ( $@ =~ /.*Error:.* ‘\.\/testexe o o o e o o o s’ interrupted by signal.*/ );
-
-        # util::subcommand()
-        ( util::execute( "$0" ) == ::E_SUB_MISSING ) || die;
-        ( util::execute( "$0 foo" ) == ::E_SUB_UNKNOWN ) || die;
-        ( util::execute( "$0 worker" ) == ::E_SUB_UNKNOWN ) || die;
-        ( util::execute( "$0 devel" ) == ::E_SUB_MISSING ) || die;
-
-        # Clean up
-        unlink( 'testexe' );
-        print( "Done.\n" );
-        dbg::leave();
     }
 }
 
